version: '3.8'
services:
  hue-gpt:
    build:
      context: ./services/hue-gpt
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
    user: "nextjs"
    env_file:
      - ./services/hue-gpt/.env.local

  walkie-talkie-server:
    build:
      context: ./services/walkie-talkie/server
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 4002:4002
    environment:
      - NODE_ENV=production
      - PORT=4002

  walkie-talkie-client:
    build:
      context: ./services/walkie-talkie/app
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3001
    user: "nextjs"
