version: '3.8'
services:
  hue-gpt:
    build:
      context: ./services/hue-gpt
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
    user: "nextjs"
    env_file:
      - ./services/hue-gpt/.env.local
    logging:
      driver: journald

  walkie-talkie-server:
    build:
      context: ./services/walkie-talkie/server
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 4002:4002
    environment:
      - NODE_ENV=production
      - PORT=4002
    logging:
      driver: journald

  walkie-talkie-client:
    build:
      context: ./services/walkie-talkie/app
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3001
    user: "nextjs"
    logging:
      driver: journald

  fleet-globe-server:
    build:
      context: ./services/fleet-globe/backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=production
      - PORT=8080
    logging:
      driver: journald

  fleet-globe-client:
    build:
      context: ./services/fleet-globe/frontend
      dockerfile: Dockerfile
    ports:
      - 4173:4173
    environment:
      - NODE_ENV=production
      - PORT=4173
    logging:
      driver: journald
